name: aoc19
version: '0.0.0'
category: template
synopsis: Advent of Code, 2019 edition
description: >
  Advent of Code, 2019 edition
author: Thomas Peiselt
github: dispanser/aoc19
license: Unlicense

ghc-options: -Wall
dependencies:
  - base >= 4.8.0 && <5

library:
  source-dirs: src
  dependencies:
    # - random
    - containers
    - unordered-containers
    - hashable
    - vector
    # - microlens
    # - Chart

tests:
  doctest:
    main: doctest-driver.hs
    source-dirs:
      - test/doctest
    dependencies:
      - doctest
      - doctest-discover

executables:
    aoc:
        source-dirs: aoc
        main: AdventOfCode.hs
        dependencies:
            - aoc19 
            - bytestring
            - split
            - vector
        ghc-options:
            - -threaded
            - -rtsopts
            - -with-rtsopts=-N
            - -main-is AdventOfCode


